### ISSUE TITLE
Block Demo Position And Rotation Sync Code Doesn't Seem To Work

### ISSUE THREAD

**Issue by glitchland** [DarkRiftNetworking/BlockDemoDarkRiftPlugin#1]
The following code example doesn't seem to work anymore:

```
//Deserialize the new position
Vec3 newPosition = message.Deserialize<Vec3>();
Vec3 newRotation = message.Deserialize<Vec3>();

lock (player)
 {
``` 

https://github.com/DarkRiftNetworking/BlockDemoDarkRiftPlugin/blob/master/BlockDemoDarkRiftPlugin/BlockDemoPlayerManager.cs#L115-L118

I think this might need to be:    

```    
using (Message message = e.GetMessage() as Message)
{
    DarkRiftReader reader = message.GetReader();
    ...
    ...
    //Deserialize the new position and rotation
    Vec3 newPosition = reader.ReadSerializable<Vec3>();
    Vec3 newRotation = reader.ReadSerializable<Vec3>();
```

**Comment by JamJar00** [comment]
Hi!
Someone just reported this issue to me and it seems I completely missed your issue, sorry! Thanks for spotting it!

You seem to have created the pull request for your fork, can you create a pull request to this repo instead so I can merge it?

Jamie

**Comment by JamJar00** [comment]
I've gone ahead and fixed this anyway since it was fairly simple! Thanks for finding it!
